# .github/workflows/ansible.yml
name: Run Ansible Playbook

on:
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest

    env:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H your.server.ip >> ~/.ssh/known_hosts

      - name: Run Playbook
        run: ansible-playbook -i inventory.ini playbook.yml
